### ISSUE TITLE
Outdated app

### ISSUE THREAD

**Issue by NdyGen** [ralfvd/nl.mindergas#2]
Can this app bu updated so it can be installed on the latest homey firmware. I now get a message that it's incompatible.

thnx

**Comment by ralfvd** [comment]
Are you using the 3.0 firmware version?

**Comment by NdyGen** [comment]
No, I'm using 2.5.2 but whenever I got to the install option of the app, the install button is grayed out and the text below it says"this app is incompatible with your Homey software version

**Comment by ralfvd** [comment]
I see what you mean, I’ve submitted a new version for approval which should
fix this issue.

I will let you know as soon as it is available.

**Comment by NdyGen** [comment]
thnx

**Comment by ralfvd** [comment]
A new version is available in the app store, please try and let me know if this works for you. Thanks for submitting the bug!

**Comment by NdyGen** [comment]
Works like a charm.

Thnx!
